# -*- coding: utf-8 -*-
"""Week 8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/Akhash-kumar-10/99cf4b827342eddb181d5cc658130137/untitled12.ipynb
"""

!pip install -q streamlit

from google.colab import drive
drive.mount('/content/gdrive')

!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip

!unzip ngrok-stable-linux-amd64.zip

! /content/ngrok  authtoken 2OeZzfThqjeB94xb0LMibAonvUB_4giiMKCYkrFANWhwVwK9F

get_ipython().system_raw('./ngrok http 8501 &')

!curl -s http://localhost:4040/api/tunnels | python3 -c \
    'import sys, json; print("Execute the next cell and the go to the following URL: " +json.load(sys.stdin)["tunnels"][0]["public_url"])'

!streamlit run /content/gdrive/MyDrive/streamlit.py